# Site settings
title: Jacob Hutchinson
name: Jacob Hutchinson

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/jacobhutchinson
 - title: LinkedIn
   url: https://www.linkedin.com/in/jacob-m-hutchinson

#Any buzzword skills you want to include
skills:
 - Machine Learning
 - Natural Language Processing
 - Deep Learning
 - Tensorflow
 - PyTorch
 - Keras
 - NLTK
 - Python
 - R
 - SQL
 - Jupyter

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default

#Work experience is required
roles:
 - title: Software Engineer Intern
   start: 2017
   end: 2017
   employer: United States Air Force Research Lab
   description: Worked for United States Air Force Research Lab in Rome, NY with the Satellite Team for a six month internship with Top Secret clearance. During that time I helped develop and reasearch Machine Learning approaches to technical question answering and other problems and gained insight from world-class researchers.

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2020
   subject: Computer Science
   school: Northeastern University
 - level: Deep Learning Certificate
   date: 2021
   subject: DeepLearning.ai
   school: Coursera.org

#This section is optional (as is the image link below)
coursera:
  profileurl: https://www.coursera.org/user/5a0b159e6cd1c3ed538f5047e3f4f493
  courses:
    - title: Machine Learning
      link: https://www.coursera.org/learn/machine-learning/
      optionalimage: https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/http://coursera-university-assets.s3.amazonaws.com/e8/7cc3d09d3f11e698dfff46d35f2da1/Stanford_Coursera_Logo.png?auto=format%2Ccompress&dpr=1&w=56px&h=56px&auto=format%2Ccompress&dpr=1&w=&h=
      date: February 19, 2020
    - title: Neural Networks and Deep Learning
      link: https://www.coursera.org/learn/neural-networks-deep-learning
      optionalimage: https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/57/4be3fd8d16487ab9cfa7bba909b236/GreyLogoName1000x1000.png?auto=format%2Ccompress&dpr=2&w=100&h=100&fit=crop
      date: October 13, 2020
    - title: Improving Deep Neural Networks
      link: https://www.coursera.org/learn/deep-neural-network
      optionalimage: https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/57/4be3fd8d16487ab9cfa7bba909b236/GreyLogoName1000x1000.png?auto=format%2Ccompress&dpr=2&w=100&h=100&fit=crop
      date: October 15, 2020
    - title: Structuring Machine Learning Projects
      link: https://www.coursera.org/learn/machine-learning-projects
      optionalimage: https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/57/4be3fd8d16487ab9cfa7bba909b236/GreyLogoName1000x1000.png?auto=format%2Ccompress&dpr=2&w=100&h=100&fit=crop
      date: October 17, 2020
    - title: Convolutional Neural Networks
      link: https://www.coursera.org/learn/convolutional-neural-networks
      optionalimage: https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/57/4be3fd8d16487ab9cfa7bba909b236/GreyLogoName1000x1000.png?auto=format%2Ccompress&dpr=2&w=100&h=100&fit=crop
      date: December 3, 2020
    - title: Sequence Models
      link: https://www.coursera.org/learn/nlp-sequence-models
      optionalimage: https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/57/4be3fd8d16487ab9cfa7bba909b236/GreyLogoName1000x1000.png?auto=format%2Ccompress&dpr=2&w=100&h=100&fit=crop
      date: January 25, 2021

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
#speakerdeck:
#   profileurl: https://speakerdeck.com/robhinds
#   talks:
#    - title: Product Management for Engineers
#      speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
#      conference: API Conference, Berlin 2018
#    - title: Agile Machine Learning - from Theory to Production
#      speakerdeckId: ec84f2f56e9743afb0675b1eeeb6b6ce
#      conference: W-JAX Conference, Munich 2017 (London 2017)

#List of interesting Github repo/projects to include - optional
github:
  - jacobhutchinson/speech-commands
  - jacobhutchinson/Job-Site-Web-Scraper

#Stackoverflow flair is optional
#stackoverflow:
#   profileurl: https://stackoverflow.com/users/258813/rhinds
#   flairimageurl: https://stackoverflow.com/users/flair/258813.png

intro: |
  I am a recent graduate with a Bachelor's of Science in Computer Science from Northeastern University. Riding out this pandemic as well as can be expected and learning all the while. I have experience in Machine Learning, Deep Learning and Natural Language processing, in theory and in practice. I took several relevant classes while in college and began seeking out online classes myself in order to learn more and get ready for the workforce. While responsibly quarantining during this pandemic I have begun to upgrade my skills toolbox to include FILL IN <br/><br/>
  FILL IN PARAGRAPH ABOUT PROJECTS<br/><br/>
  FILL IN WORK EXPERIENCE/CALL-TO-ACTION, also if you're seeing this then sorry about that, this site's not done yet nor am I done learning. I will fill in the above when I officially start full-time job searching after I round out my skillset with more online classes<br/><br/>

# An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>NLP Speech Commands</strong>: Description goes here</a>.<br/><br/>
   <strong>Job Site Scraper and Visualizer</strong>: Description goes here</a>.<br/><br/>
